### PR TITLE
Disable SEMAPHORE code block in cp0.cpp

### LINKED ISSUE #242: 0.5.8 - Regression in paraLLEl RSP
Banjo Tooie (U) is broken when using paraLLEl RSP + RDP, this can be seen right at the beginning, in the intro sequence.

0.5.7 - correct behavior:
image

0.5.8 - the camera is stuck in the wrong place:
image

### PR DESCRIPTION
**Pull request by Rosalie241**
Fixes https://github.com/Rosalie241/RMG/issues/242

Pinging @mpharoah for visibility aswell

### CODE REVIEW

**Comment by m4xw** [comment]
Bandaid

**Comment by mpharoah** [comment]
It looks like in Banjo Tooie, the RSP is spinning on the semaphore register, waiting for the CPU to write to it. To avoid freezing when a program does exactly this, the emulator will yield back to the CPU after too many reads from the RSP CPU0 status register or reads from the semaphore register when it is locked (value 1). Then semaphore is then released by the CPU, and then next time the RSP is run, it can continue on.

This is how it's supposed to work, and it is exactly what's happened in parallel-rsp; however, this camera issue appears. Changing the behaviour so that the RSP never actually locks the semaphore-- which is what is being done in this PR - fixes this bug in BT; however, this is _not_ correct behaviour.

It assume this hack to not correctly emulate the test-and-set behaviour of the semaphore register is just fixing some other unknown inaccuracy by introducing a new inaccuracy that happens to bypass the true bug.

I'll continue looking into this, but simply removing the lines like in this PR is absolutely not a long term fix, and may actually break other things, as synchronization between the RSP and CPU is now broken when using the semaphore register for that purpose.

That being said, the semaphore register is usually just used for ensuring the CPU and RSP don't try to DMA at the same time, so inaccurate emulation of the sempahore register is _probably_ not going to break many retail roms (in fact it was broken before). But it seems like BT is using the register more generally for synchronization between the RSP and CPU on startup, and correctly emulating this is somehow breaking something.

**Comment by mpharoah** [comment]
Actually, I think it might be that when the RSP yields back to the CPU due to repeated attempts to "acquire a lock" using the semaphore, it might actually be discarding the rest of the RSP instructions instead of continuing next time. At least, the next time it runs RSP code, its no longer trying to read from the semaphore register.

**Comment by mpharoah** [comment]
Then the reason that it "works" with the change reverted is because waiting for the CPU by double reading the semaphore won't actually work since it's not emulating the test-and-set behaviour so it simply just proceeds, thinking that the CPU has done its stuff and released the semaphore by writing to it when it actually hasn't done anything. And somehow, it still works.

So with this PR in, disabling the write-on-read behaviour of the semaphore register, the inaccuracy is that the CPU and RSP won't synchronize when using the semaphore for this purpose. But _without_ this PR, trying to sync the CPU and RSP this way results in RSP code being lost, which is worse. To do it correctly, it needs to resume the RSP code after the CPU releases the semaphore instead of just having it clobbered by new RSP instructions before it gets to run again. I'll bet this would also make the concurrency test in n64-systemtests pass. I'll see if I can get that working, but it's going to need changes on the core side as well.

**Comment by mpharoah** [comment]
Confirmed. Changing the emulator core to resume RSP execution when the CPU writes to the RSP semaphore register and it was non-zero. Going to do a bit more testing.

**Comment by mpharoah** [comment]
Is extending `m64p_plugin.h` a problem? 

EDIT: actually I can just use `extern` instead

**Comment by mpharoah** [comment]
Here's my proper fix for this issue:
https://gitlab.com/parallel-launcher/parallel-n64/-/compare/d15b5a3a2ec7a9451ef01c3b278c196e6031f3b1...f2f72c2efdac810a198f901fccf04798ef96d9e1?from_project_id=34649479&straight=false

As you can see, it requires data to be shared between the core and the RSP. I can make a PR to fix parallel-rsp, but its going to have to depend on changes in the emulator cores as well. Is that fine with you, or should I add another define or something to gate the core version?

**Comment by Rosalie241** [comment]
That fix won't work with upstream mupen64plus due to the plugin design FYI

**Comment by 03bgood** [comment]
In Jolly Roger Lagoon, if you warp from "Big Fish Cavern" or "Locker's Cavern" back to "Town Center", the music goes completely silent until you go through a loading zone (i.e. Jolly's Bar). This doesn't happen at all with "GLideN64" and the music plays fine when warping from those two aforementioned locations. Oddly enough, warping from "Atlantis" won't trigger the music stopping glitch, so what's going on?

A similar glitch like this also occurs in Donkey Kong 64 during a bonus challenge after the introduction music plays and the timer starts, the actual bonus stage music doesn't play or eventually starts after about 10-15 seconds.

**Comment by m4xw** [comment]
Likely not related

**Comment by m4xw** [comment]
> Is extending `m64p_plugin.h` a problem?
> 
> EDIT: actually I can just use `extern` instead

You need to extend it, then add a version and the extra value here https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/mupen64plus-core/src/plugin/plugin.c#L320-L351 (take the gfx as reference impl)

`extern` will only work for -nx and parallel

**Pull request merged**
